spring:
  datasource:
    url: jdbc:h2:./Documents/h2/bin/hotfka
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create

  h2:
    console:
      enabled: true
      path: /h2-console